apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot2-may1-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/chatbot2-may1-1:03f29e240d19edebb5df98338e520c53c84655b1@sha256:64422f20499b67edce972af30948e4bc55deac953cc0e4f56c1cf0e6003c9d18 # use pre-built to bootstrap
          name: app-inference
